---
apiVersion: v1
kind: Service
metadata:
  name: rh-workshops-svc
  namespace: rh-workshops
  labels:
    app: rh-workshops
    app.kubernetes.io/name: rh-workshops
    app.kubernetes.io/part-of: rh-workshops
spec:
  ports:
    - port: 8080
      name: web
  selector:
    app: rh-workshops
